time_range:
   start: ''
   end: ''
   flag: milli

info_1: [04668, warning]

info_2: ['344383e1:93d']

type_1: [PCM]

data_1: ['unexpected exception']

bundle_1: ['vm-996']

criteria_for_primary:
   name: "primary site criterion"
   time: time_range
   info: []
   type: []
   data: []
   bundle: []
   logfilename: "PrimarySiteResult"


PrimarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/realpp/
   type: config
   dayoffset: 0


SecondarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/sslog/
   type: config
   dayoffset: 1

sites: [PrimarySite]
