time_range:
   start: '2013-07-23T20:30:09.705+02:00'
   end: '2013-07-24T06:13:24.722+02:00'
   flag: milli

info_1: [04668, warning]

info_2: ['344383e1:93d']

type_1: [PCM]

data_1: ['unexpected exception']

bundle_1: ['vm-996']

criteria_for_primary:
   name: "primary site criterion"
   time: time_range
   info: [info_1, info_2]
   type: [type_1]
   data: [data_1]
   bundle: [bundle_1]
   logfilename: "PrimarySiteResult"


PrimarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/pplog/
   type: config
   dayoffset: 1


SecondarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/sslog/
   type: config
   dayoffset: 1

sites: [PrimarySite, SecondarySite]
