time1:
   start: "2013-07-23T20:30:09.705+02:00"
   end: "2013-07-23T23:26:02.930+02:00"
   flag: "milli"

info1: ["03528", "error"]
type1: ["PCM"]
data1: ["com.vmware.vcDr.ProtectedVmRemovedEvent"]
bundle1: ["System.Read"]

srmsite1_criteria:
   name: "Site1Criria"
   time: "time1"
   info: ["info1"]
   type: ["type1"]
   data: ['data1']
   bundle: ['bundle1']
   logfilename: "ha_result"

srmSite1:
   criteria: ["srmsite1_criteria"]
   name: "SrmSite1"
   dir: "/myfiles/Source/vsProject/srmparserlite/pplog"
   type: "config"
   dayoffset: 1

sites: ["srmSite1"]
