time_range:
   start: '2013-04-29T15:55:03.005-04:00'
   end: ''
   flag: hour

info_1: [02316]

info_2: ['ThreadPool']

type_1: [PCM]

data_1: ['unexpected exception']

bundle_1: ['vm-996']

criteria_for_primary:
   name: "primary site criterion"
   time: time_range
   info: []
   type: []
   data: []
   bundle: []
   logfilename: "PrimarySiteResult"


PrimarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/realpp/
   type: sync
   dayoffset: 0


SecondarySite:
   criteria: [criteria_for_primary]
   name: PrimarySite
   dir: /myfiles/Source/vsProject/logs/realss/
   type: config
   dayoffset: 1

sites: [PrimarySite, SecondarySite]
