time1:
   start: "2013-07-23T20:30:09.705+02:00"
   end: "2013-07-23T21:34:31.145+02:00"
   flag: "milli"

time2:
   start: "2013-07-23T20:30:09.705+02:00"
   end: "2013-07-24T08:59:47.068+02:00"
   flag: "milli"

info1: ["04244", "error"]
info2: ["04764", "verbose"]
info3: ["PersistableRWLock"]
type1: ["PCM"]
data1: ["com.vmware.vcDr.ProtectedVmRemovedEvent"]
bundle1: ["test"]
bundle2: ["group-v965"]

srmsite1_criteria:
   name: "Site1Criria"
   time: "time1"
   info: [info1]
   type: []
   data: []
   bundle: [bundle1]
   logfilename: "ha1_1_result"

srmsite21_criteria:
   name: "Site21Criria"
   time: "time2"
   info: [info2]
   type: []
   data: []
   bundle: [bundle2]
   logfilename: "Ha2_1_result"

srmsite22_criteria:
   name: "Site22Criria"
   time: "time1"
   info: ['info3']
   type: []
   data: []
   bundle: []
   logfilename: "Ha2_2_result"

srmSite1:
   criteria: ["srmsite1_criteria"]
   name: "SrmSite1"
   dir: /myfiles/Source/vsProject/logs/rpplog/
   type: "config"
   dayoffset: 1

srmSite2:
   criteria: ["srmsite21_criteria"]
   name: "SrmSite2"
   dir: /myfiles/Source/vsProject/logs/rsslog/
   type: "config"
   dayoffset: 1

sites: ["srmSite1", "srmSite2"]
